"""Initial schema: events + pos_transactions tables.

Revision ID: 001
Revises:
Create Date: 2026-06-02
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        # deterministic UUID generated by the app for dedup
        sa.Column("event_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("store_id", sa.Text(), nullable=False),   # normalized store identifier
        sa.Column("camera_id", sa.Text(), nullable=False),
        sa.Column("event_ts", sa.TIMESTAMP(timezone=True), nullable=False),

        # entry / exit fields
        sa.Column("id_token", sa.Text()),
        sa.Column("is_staff", sa.Boolean()),
        sa.Column("gender_pred", sa.CHAR(1)),
        sa.Column("age_pred", sa.SmallInteger()),
        sa.Column("age_bucket", sa.Text()),
        sa.Column("is_face_hidden", sa.Boolean()),
        sa.Column("group_id", sa.Text()),
        sa.Column("group_size", sa.SmallInteger()),

        # zone / queue shared fields
        sa.Column("track_id", sa.Integer()),
        sa.Column("zone_id", sa.Text()),
        sa.Column("zone_name", sa.Text()),
        sa.Column("zone_type", sa.Text()),
        sa.Column("is_revenue_zone", sa.Boolean()),
        sa.Column("zone_hotspot_x", sa.Float()),
        sa.Column("zone_hotspot_y", sa.Float()),
        sa.Column("gender", sa.CHAR(1)),
        sa.Column("age", sa.SmallInteger()),

        # queue-specific fields
        sa.Column("queue_event_id", postgresql.UUID(as_uuid=True)),
        sa.Column("queue_join_ts", sa.TIMESTAMP(timezone=True)),
        sa.Column("queue_served_ts", sa.TIMESTAMP(timezone=True)),
        sa.Column("queue_exit_ts", sa.TIMESTAMP(timezone=True)),
        sa.Column("wait_seconds", sa.Integer()),
        sa.Column("queue_position_at_join", sa.SmallInteger()),
        sa.Column("abandoned", sa.Boolean()),

        # full original payload for reprocessing
        sa.Column("raw", postgresql.JSONB(), nullable=False),
        sa.Column("ingested_at", sa.TIMESTAMP(timezone=True),
                  server_default=sa.text("now()"), nullable=False),

        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", name="uq_events_event_id"),
    )

    # query patterns: store+time range, store+type+time, heatmap, session replay
    op.create_index("ix_events_store_ts",        "events", ["store_id", "event_ts"])
    op.create_index("ix_events_store_type_ts",   "events", ["store_id", "event_type", "event_ts"])
    op.create_index("ix_events_store_zone_ts",   "events", ["store_id", "zone_id", "event_ts"])
    op.create_index("ix_events_id_token",        "events", ["id_token"])
    op.create_index("ix_events_track_store",     "events", ["track_id", "store_id"])
    op.create_index(
        "ix_events_queue_event_id", "events", ["queue_event_id"],
        postgresql_where=sa.text("queue_event_id IS NOT NULL"),
    )

    op.create_table(
        "pos_transactions",
        sa.Column("txn_id",    sa.Text(), nullable=False),
        sa.Column("store_id",  sa.Text(), nullable=False),
        sa.Column("txn_ts",    sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("amount",    sa.Numeric(10, 2)),
        sa.Column("items",     sa.Integer()),
        sa.Column("id_token",  sa.Text()),
        sa.Column("ingested_at", sa.TIMESTAMP(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("txn_id"),
    )
    op.create_index("ix_pos_store_ts", "pos_transactions", ["store_id", "txn_ts"])


def downgrade() -> None:
    op.drop_index("ix_pos_store_ts",           table_name="pos_transactions")
    op.drop_table("pos_transactions")

    op.drop_index("ix_events_queue_event_id",  table_name="events")
    op.drop_index("ix_events_track_store",     table_name="events")
    op.drop_index("ix_events_id_token",        table_name="events")
    op.drop_index("ix_events_store_zone_ts",   table_name="events")
    op.drop_index("ix_events_store_type_ts",   table_name="events")
    op.drop_index("ix_events_store_ts",        table_name="events")
    op.drop_table("events")
